repos:
- repo: local
  hooks:
  - id: autoflake
    name: autoflake
    entry: autoflake
    language: python
    files: \.py$
    exclude: (__init__.py|conftest.py)
    args: ['--in-place', '--remove-all-unused-imports']
    additional_dependencies: ["autoflake==1.4"]

  - id: isort
    name: isort
    entry: isort
    language: python
    files: \.py$
    additional_dependencies: ["isort==5.6.4", "toml==0.10.1"]

  - id: black
    name: black
    entry: black
    language: python
    files: \.py$
    additional_dependencies: ["black==20.8b1 "]
