"""add plugin_storage table

Revision ID: 164947b70981
Revises: 64d6f19a2d87
Create Date: 2020-02-22 18:57:18.910266

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "164947b70981"
down_revision = "64d6f19a2d87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plugin", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plugin_storage")),
    )
    op.create_index("ix_plugin_key", "plugin_storage", ["plugin", "key"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plugin_key", table_name="plugin_storage")
    op.drop_table("plugin_storage")
    # ### end Alembic commands ###
