"""add graphical fortunkas

Revision ID: 164f07c07d3b
Revises: 3e53f9ffa04b
Create Date: 2020-04-09 17:10:26.199982

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "164f07c07d3b"
down_revision = "3e53f9ffa04b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fortunki", sa.Column("image", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_fortunki_image_b2_images"), "fortunki", "b2_images", ["image"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_fortunki_image_b2_images"), "fortunki", type_="foreignkey"
    )
    op.drop_column("fortunki", "image")
    # ### end Alembic commands ###
