"""add sucharki table

Revision ID: 1ad2b287f7ad
Revises: c2d2f403fb8c
Create Date: 2020-02-16 15:39:52.424935

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ad2b287f7ad"
down_revision = "c2d2f403fb8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sucharki",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image", sa.LargeBinary(), nullable=False),
        sa.Column("digest", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sucharki")),
    )
    op.create_index(op.f("ix_sucharki_digest"), "sucharki", ["digest"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sucharki_digest"), table_name="sucharki")
    op.drop_table("sucharki")
    # ### end Alembic commands ###
