"""add column reminders_sent

Revision ID: 2f9ff37d9863
Revises: 41feb31d888c
Create Date: 2021-01-27 20:55:52.522421

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f9ff37d9863"
down_revision = "41feb31d888c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("reminders_sent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "reminders_sent")
    # ### end Alembic commands ###
