"""add credentials table

Revision ID: 3e53f9ffa04b
Revises: 164947b70981
Create Date: 2020-03-03 20:07:11.222194

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e53f9ffa04b"
down_revision = "164947b70981"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("login", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("login", name=op.f("pk_credentials")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credentials")
    # ### end Alembic commands ###
