"""add feels table

Revision ID: 4923fb2ba581
Revises: 567424e5046c
Create Date: 2019-09-28 22:12:58.413603

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4923fb2ba581"
down_revision = "567424e5046c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feels")),
        sa.UniqueConstraint("url", name=op.f("uq_feels_url")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feels")
    # ### end Alembic commands ###
