"""add post_id to sucharki table

Revision ID: 49921318845a
Revises: 1ad2b287f7ad
Create Date: 2020-02-17 11:45:02.980594

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49921318845a"
down_revision = "1ad2b287f7ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sucharki", sa.Column("post_id", sa.Text(), nullable=True))
    op.create_index(op.f("ix_sucharki_post_id"), "sucharki", ["post_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sucharki_post_id"), table_name="sucharki")
    op.drop_column("sucharki", "post_id")
    # ### end Alembic commands ###
