"""add fortunki table

Revision ID: 567424e5046c
Revises: f32a45256434
Create Date: 2019-09-19 18:59:11.629057

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "567424e5046c"
down_revision = "f32a45256434"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fortunki",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fortunki")),
        sa.UniqueConstraint("text", name=op.f("uq_fortunki_text")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fortunki")
    # ### end Alembic commands ###
