"""allow duplicated hashes

Revision ID: 64d6f19a2d87
Revises: 7d4b64c80a5c
Create Date: 2020-02-22 15:55:09.872071

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "64d6f19a2d87"
down_revision = "7d4b64c80a5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_b2_images_hash"), "b2_images", ["hash"], unique=False)
    op.drop_constraint("uq_b2_images_hash", "b2_images", type_="unique")
    op.drop_constraint("uq_b2_images_url", "b2_images", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_b2_images_url", "b2_images", ["url"])
    op.create_unique_constraint("uq_b2_images_hash", "b2_images", ["hash"])
    op.drop_index(op.f("ix_b2_images_hash"), table_name="b2_images")
    # ### end Alembic commands ###
