"""drop sucharki table

Revision ID: 7c1806a11b22
Revises: e6c37c0c6006
Create Date: 2020-02-21 23:12:19.863228

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c1806a11b22"
down_revision = "e6c37c0c6006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sucharki_digest", table_name="sucharki")
    op.drop_index("ix_sucharki_post_id", table_name="sucharki")
    op.drop_table("sucharki")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sucharki",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("image", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("digest", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("post_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_sucharki"),
    )
    op.create_index("ix_sucharki_post_id", "sucharki", ["post_id"], unique=True)
    op.create_index("ix_sucharki_digest", "sucharki", ["digest"], unique=True)
    # ### end Alembic commands ###
