"""drop external_id column

Revision ID: 91bbe001dfd7
Revises: 7c1806a11b22
Create Date: 2020-02-21 23:50:59.426897

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91bbe001dfd7"
down_revision = "7c1806a11b22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_b2_images_external_id", "b2_images", type_="unique")
    op.drop_column("b2_images", "external_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "b2_images",
        sa.Column("external_id", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        "uq_b2_images_external_id", "b2_images", ["external_id"]
    )
    # ### end Alembic commands ###
