"""add server_default in b2_images

Revision ID: bacf2c228b0f
Revises: 91bbe001dfd7
Create Date: 2020-02-22 00:51:33.938046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bacf2c228b0f"
down_revision = "91bbe001dfd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "b2_images",
        "deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        server_default="false",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("b2_images", "deleted", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
