"""remove feels table

Revision ID: c2d2f403fb8c
Revises: 4923fb2ba581
Create Date: 2020-02-14 20:23:25.494070

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2d2f403fb8c"
down_revision = "4923fb2ba581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feels")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feels",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_feels"),
        sa.UniqueConstraint("url", name="uq_feels_url"),
    )
    # ### end Alembic commands ###
