name: build

on:
  push:
    branches:
      - master

jobs:
  pytest:
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: qbot_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install libpq-dev  # required by psycopg2
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run alembic migrations
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/qbot_test
      run: |
        alembic upgrade head
    - name: Run pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/qbot_test
      run: |
        pytest
    - name: Revert migrations
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/qbot_test
      run: |
        alembic downgrade base

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run autoflake
        run: |
          pre-commit run autoflake --all-files --show-diff-on-failure
      - name: Run isort
        run: |
          pre-commit run isort --all-files --show-diff-on-failure
      - name: Run black
        run: |
          pre-commit run black --all-files --show-diff-on-failure
  deploy:
    needs: [pytest, lint]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Push to Dokku
        uses: landmaj/github-action-dokku@master
        with:
          PRIVATE_KEY: ${{ secrets.DOKKU_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.DOKKU_PUBLIC_KEY }}
          HOST: ${{ secrets.DOKKU_HOST }}
          PROJECT: qbot
