name: lint

on: [push]

jobs:
  autoflake:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: |
          pre-commit run autoflake --all-files
  isort:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: |
          pre-commit run isort --all-files
  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: |
          pre-commit run black --all-files
