name: tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      run: |
        pytest
